[package]
name = "abg-code-algorithms"
version = "0.1.0"
authors = ["Liam Dawson <liam@ldaws.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
thiserror = "1.0"
prettytable-rs = "^0.8"
